//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEscuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Alumno
    {
        public int ID_Alumno { get; set; }
        public string NoControl { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.DateTime FechaDeNacimiento { get; set; }
        public Nullable<int> ID_CARRERA { get; set; }
        public virtual Tb_Carrera Tb_Carrera { get; set; }
    }
}
