//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEscuela.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_Alumno
    {
        [Display(Name = "#")]
        public int ID_Alumno { get; set; }
        public string NoControl { get; set; }
        [Display(Name = "Nombre del Alumno")]
        public string Nombres { get; set; }
        [Display(Name = "Apellido Paterno")]
        public string ApellidoPaterno { get; set; }
        [Display(Name = "Apellido Materno")]
        public string ApellidoMaterno { get; set; }
        [Display(Name = "¿Está Activo?")]
        public Nullable<bool> Activo { get; set; }
        [Display(Name = "Fecha de nacimiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime FechaDeNacimiento { get; set; }
        [Display(Name = "Carrera")]
        public string Carrera { get; set; }
    }
}
