//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEscuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Carrera
    {
        public Tb_Carrera()
        {
            this.Tb_Alumno = new HashSet<Tb_Alumno>();
        }
    
        public int ID_Carrera { get; set; }
        public string Carrera { get; set; }
    
        public virtual ICollection<Tb_Alumno> Tb_Alumno { get; set; }
    }
}
